version: '2'
services:
  leassetsserver-app:
    image: leassetsserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://leassetsserver-postgresql:5432/leassetsServer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://leassetsserver-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://leassetsserver-elasticsearch:9200
    ports:
      - 8080:8080
  leassetsserver-postgresql:
    extends:
      file: postgresql.yml
      service: leassetsserver-postgresql
  leassetsserver-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: leassetsserver-elasticsearch
