#
# Leassets Server - Leases and assets management platform
# Copyright © 2021 Edwin Njeru (mailnjeru@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

version: '2'
services:
  leassetsserver-app:
    image: ghacupha/leassets-server:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/leassetsServer
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://leassetsserver-postgresql:5432/leassetsServer
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://leassetsserver-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://leassetsserver-elasticsearch:9200
      - UPLOADS_SIZE=${UPLOADS_SIZE}
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
    ports:
      - 9100:9100
  #  leassetsserver-postgresql:
  #    extends:
  #      file: postgresql.yml
  #      service: leassetsserver-postgresql
  leassetsserver-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: leassetsserver-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
